// Code generated by go generate; DO NOT EDIT.
// This file was generated by github.com/gentee/gentee/vm/generate/generate.go at
// 2019/09/26 10:26:52 +05

package vm

import "github.com/gentee/gentee/core"

var EmbedFuncs = []core.Embed{
	{"Add", "int,int", "int", core.ADD, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"BitAnd", "int,int", "int", core.BITAND, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"BitNot", "int", "int", core.BITNOT, nil, core.TYPEINT, []uint16{core.TYPEINT}, false, false, false},
	{"BitOr", "int,int", "int", core.BITOR, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"BitXor", "int,int", "int", core.BITXOR, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"Div", "int,int", "int", core.DIV, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, true},
	{"Equal", "int,int", "bool", core.EQ, nil, core.TYPEBOOL, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"Greater", "int,int", "bool", core.GT, nil, core.TYPEBOOL, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"Less", "int,int", "bool", core.LT, nil, core.TYPEBOOL, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"LShift", "int,int", "int", core.LSHIFT, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, true},
	{"Mod", "int,int", "int", core.MOD, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, true},
	{"Mul", "int,int", "int", core.MUL, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
	{"RShift", "int,int", "int", core.RSHIFT, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, true},
	{"Sign", "int", "int", core.SIGN, nil, core.TYPEINT, []uint16{core.TYPEINT}, false, false, false},
	{"Sub", "int,int", "int", core.SUB, nil, core.TYPEINT, []uint16{core.TYPEINT,core.TYPEINT}, false, false, false},
}