// Copyright 2019 Alexey Krivonogov. All rights reserved.
// Use of this source code is governed by a MIT license
// that can be found in the LICENSE file.

package stdlibvm

import "github.com/gentee/gentee/core"

var Embedded = []core.Embed{
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEBOOL}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEINT}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPEINT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEINT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEBOOL}},
	{Func: nil, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPESTR},
		CanError: true},
	// 10
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEINT},
		CanError: true},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEBOOL},
		CanError: true},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPECHAR, core.TYPECHAR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPECHAR, core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPECHAR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPECHAR}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPECHAR, core.TYPECHAR}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPECHAR, core.TYPECHAR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPECHAR}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEINT}},
	// 20
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEINT, core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEINT, core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT, core.TYPEINT},
		CanError: true},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEINT, core.TYPEFLOAT},
		CanError: true},
	// 30
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEINT, core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPEARR, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPEINT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPEINT, core.TYPEINT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, Variadic: true},
	// 40
	{Func: ReadFileºStr, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEARR, core.TYPESTR}},
	{Func: nil, Return: core.TYPEARR, Params: []uint16{core.TYPEARR}},
	{Func: nil, Return: core.TYPEARR, Params: []uint16{core.TYPESTR, core.TYPESTR}},
	{Func: nil, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEBUF}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEBUF}},
	{Func: nil, Return: core.TYPEBUF, Params: []uint16{core.TYPEBUF, core.TYPEINT,
		core.TYPEBUF}, CanError: true},
	{Func: nil, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR}, CanError: true},
	// 50
	{Func: nil, Return: core.TYPEBUF, Params: []uint16{core.TYPEBUF, core.TYPEBUF}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPEBUF}},
	{Func: nil, Return: core.TYPEBUF, Params: []uint16{core.TYPEBUF, core.TYPEINT,
		core.TYPEINT}, CanError: true},
	{Func: nil, Return: core.TYPEBUF},
	{Func: Print, Return: core.TYPEINT, Variadic: true, CanError: true},
	{Func: Println, Return: core.TYPEINT, Variadic: true, CanError: true},
	{Func: PrintShiftºStr, Return: core.TYPEINT, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: ReadString, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: Md5ºBuf, Return: core.TYPEBUF, Params: []uint16{core.TYPEBUF}},
	{Func: Md5ºStr, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR}},
	// 60
	{Func: Sha256ºBuf, Return: core.TYPEBUF, Params: []uint16{core.TYPEBUF}},
	{Func: Sha256ºStr, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR,
		core.TYPEINT, core.TYPEINT}, CanError: true},
	{Func: FindRegExpºStrStr, Return: core.TYPEARR, Params: []uint16{core.TYPESTR,
		core.TYPESTR}, CanError: true},
	{Func: MatchºStrStr, Return: core.TYPEBOOL, Params: []uint16{core.TYPESTR,
		core.TYPESTR}, CanError: true},
	{Func: ReplaceRegExpºStrStr, Return: core.TYPESTR, Params: []uint16{core.TYPESTR,
		core.TYPESTR, core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPESET, core.TYPEINT},
		CanError: true},
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPEARR}, CanError: true},
	{Func: AppendFileºStrBuf, Params: []uint16{core.TYPESTR, core.TYPEBUF}, CanError: true},
	// 70
	{Func: AppendFileºStrStr, Params: []uint16{core.TYPESTR, core.TYPESTR}, CanError: true},
	{Func: ChDirºStr, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: CopyFileºStrStr, Return: core.TYPEINT, Params: []uint16{core.TYPESTR, core.TYPESTR},
		CanError: true},
	{Func: CreateDirºStr, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: GetCurDir, Return: core.TYPESTR, CanError: true},
	{Func: Md5FileºStr, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: ReadFileºStrBuf, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR, core.TYPEBUF},
		CanError: true},
	{Func: ReadFileºStrIntInt, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR, core.TYPEINT,
		core.TYPEINT}, CanError: true},
	{Func: RemoveºStr, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: RemoveDirºStr, Params: []uint16{core.TYPESTR}, CanError: true},
	// 80
	{Func: RenameºStrStr, Params: []uint16{core.TYPESTR, core.TYPESTR}, CanError: true},
	{Func: Sha256FileºStr, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: TempDir, Return: core.TYPESTR},
	{Func: TempDirºStrStr, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPESTR},
		CanError: true},
	{Func: WriteFileºStrBuf, Params: []uint16{core.TYPESTR, core.TYPEBUF}, CanError: true},
	{Func: WriteFileºStrStr, Params: []uint16{core.TYPESTR, core.TYPESTR}, CanError: true},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPESTR, core.TYPESTR}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPESTR, core.TYPESTR}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPEFLOAT}},
	// 90
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT,
		core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT,
		core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPEFLOAT}},
	{Func: nil, Return: core.TYPEFLOAT, Params: []uint16{core.TYPEFLOAT, core.TYPEINT}},
	{Func: nil, Return: core.TYPEMAP, Params: []uint16{core.TYPEMAP, core.TYPESTR}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPEMAP, core.TYPESTR}},
	{Func: AbsPath, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: BaseName, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: Dir, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	// 100
	{Func: Ext, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: JoinPath, Return: core.TYPESTR, Variadic: true},
	{Func: MatchPath, Return: core.TYPEBOOL, Params: []uint16{core.TYPESTR, core.TYPESTR},
		CanError: true},
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPESET, core.TYPEINT},
		CanError: true},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPESET, core.TYPEINT},
		CanError: true},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESET}},
	{Func: nil, Return: core.TYPEARR, Params: []uint16{core.TYPESET}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPESET, core.TYPESET}},
	// 110
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPESET, core.TYPESET}},
	{Func: nil, Return: core.TYPESET, Params: []uint16{core.TYPESET}},
	{Func: nil, Return: core.TYPEBOOL, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPEINT, Params: []uint16{core.TYPESTR, core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEINT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR, core.TYPEINT}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR,
		core.TYPESTR, core.TYPESTR}},
	{Func: nil, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}},
	{Func: Download, Return: core.TYPEINT, Params: []uint16{core.TYPESTR, core.TYPESTR},
		CanError: true},
	// 120
	{Func: HTTPGet, Return: core.TYPEBUF, Params: []uint16{core.TYPESTR}, CanError: true},
	{Func: HTTPPage, Return: core.TYPESTR, Params: []uint16{core.TYPESTR}, CanError: true},
}

// AssignAddºArrStr appends one string to array
func AssignAddºArrAny(arr interface{}, value interface{}) (interface{}, error) {
	arr.(*core.Array).Data = append(arr.(*core.Array).Data, value)
	return arr, nil
}

var EmbedAny = []core.AssignAnyFunc{
	nil,
	AssignAddºArrAny,
	nil,
	nil,
	nil,
	nil,
	nil,
	nil,
	nil,
}
